// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyqdlmddcnyirkvtgyzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cWRsbWRkY255aXJrdnRneXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjQxNzMsImV4cCI6MjA3MTIwMDE3M30.Dvpp4NG2DHT7yPVI7elqgVC_rEXZBtFQuyIzXYUTSUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});