// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imkdmwsukojuhzjlmyfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlta2Rtd3N1a29qdWh6amxteWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODIyNDAsImV4cCI6MjA3NzA1ODI0MH0.Juo1wZCgbEM4HkggE8N5oNZ2XCjFXdgZjSmMZP7m3Q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});