import React from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Download, FileText, FileSpreadsheet } from 'lucide-react';
import { format } from 'date-fns';
import { DateRange } from './DateRangeFilter';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

interface ExportDropdownProps<T> {
  data: T[];
  columns: { header: string; accessorKey: keyof T | ((row: T) => any) }[];
  fileName: string;
  reportTitle: string;
  dateRange?: DateRange;
  showDateInTitle?: boolean;
}

export const ExportDropdown = <T,>({ 
  data, 
  columns, 
  fileName, 
  reportTitle, 
  dateRange,
  showDateInTitle = true
}: ExportDropdownProps<T>) => {
  const { profile, loading } = useAuth();

  const getFormattedFileName = () => {
    if (!dateRange?.from || !dateRange?.to) return fileName;
    const fromDate = format(dateRange.from, 'yyyy-MM-dd');
    const toDate = format(dateRange.to, 'yyyy-MM-dd');
    return `${fileName}-${fromDate}-to-${toDate}`;
  };

  const getFormattedReportTitle = () => {
    if (!dateRange?.from || !dateRange?.to || !showDateInTitle) return reportTitle;
    const fromDate = format(dateRange.from, 'MMM dd, yyyy');
    const toDate = format(dateRange.to, 'MMM dd, yyyy');
    return `${reportTitle} (${fromDate} - ${toDate})`;
  };

  const generatePdf = () => {
    // Check if profile is loaded
    if (loading) {
      toast.error("Please wait for user profile to load");
      return;
    }

    // Check if data exists
    if (!data || data.length === 0) {
      toast.error("No data available to export");
      return;
    }


    const doc = new jsPDF();
    
    // --- Company Header and Branding ---
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 24, 39); // Dark blue color for branding
    doc.text("Lendy Microfinance", 14, 22);
    
    // Add a line under the company name
    doc.setDrawColor(17, 24, 39);
    doc.line(14, 24, 196, 24);
    
    // Report title
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    const reportTitle = getFormattedReportTitle() || 'Report';
    doc.text(reportTitle, 14, 35);
    
    // Add date range info if available
    if (dateRange?.from && dateRange?.to) {
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      const dateInfo = `Date Range: ${format(dateRange.from, 'MMM dd, yyyy')} - ${format(dateRange.to, 'MMM dd, yyyy')}`;
      doc.text(dateInfo, 14, 45);
      doc.setTextColor(0, 0, 0);
    }
    
    // Add generation info (Generated by and timestamp)
    const currentY = dateRange?.from && dateRange?.to ? 55 : 45;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    
    // Get user identifier - prefer full_name, fallback to email, then unknown
    const userIdentifier = profile?.full_name || profile?.email || 'Unknown User';
    doc.text(`Generated by: ${userIdentifier}`, 14, currentY);
    doc.text(`Generated on: ${new Date().toLocaleString('en-KE', { 
      dateStyle: 'medium', 
      timeStyle: 'short' 
    })}`, 14, currentY + 5);
    doc.setTextColor(0, 0, 0);
    
    const head = [columns.map(c => c.header)];
    const body = data.map(row => columns.map(col => {
      if (typeof col.accessorKey === 'function') {
        const value = col.accessorKey(row);
        return value !== null && value !== undefined ? String(value) : '';
      }
      const value = row[col.accessorKey as keyof T];
      return value !== null && value !== undefined ? String(value) : '';
    }));

    autoTable(doc, {
      startY: currentY + 15, // Add more space for generation info
      head: head,
      body: body,
      theme: 'grid',
      headStyles: { fillColor: [17, 24, 39] }
    });
    doc.save(`${getFormattedFileName()}.pdf`);
  };

  const generateCsv = () => {
    // Check if profile is loaded
    if (loading) {
      toast.error("Please wait for user profile to load");
      return;
    }

    // Check if data exists
    if (!data || data.length === 0) {
      toast.error("No data available to export");
      return;
    }

    // Get user identifier - prefer full_name, fallback to email, then unknown
    const userIdentifier = profile?.full_name || profile?.email || 'Unknown User';

    const escapeCsvCell = (cell: any) => `"${String(cell).replace(/"/g, '""')}"`;
    
    // Add company branding and date range info as first rows
    let csvRows: string[] = [];
    
    // Company header
    csvRows.push("Lendy Microfinance");
    csvRows.push(""); // Empty row for spacing
    
    // Report title
    csvRows.push(getFormattedReportTitle() || 'Report');
    csvRows.push(''); // Empty row for spacing
    
    if (dateRange?.from && dateRange?.to) {
      const dateInfo = `Date Range,${format(dateRange.from, 'MMM dd, yyyy')} - ${format(dateRange.to, 'MMM dd, yyyy')}`;
      csvRows.push(dateInfo);
      csvRows.push(''); // Empty row for spacing
    }
    
    // Add generation info
    csvRows.push(`Generated by,${userIdentifier}`);
    csvRows.push(`Generated on,${new Date().toLocaleString('en-KE', { 
      dateStyle: 'medium', 
      timeStyle: 'short' 
    })}`);
    csvRows.push(''); // Empty row for spacing
    
    const headers = columns.map(c => c.header).join(',');
    const dataRows = data.map(row => columns.map(col => {
      if (typeof col.accessorKey === 'function') {
        const value = col.accessorKey(row);
        return escapeCsvCell(value !== null && value !== undefined ? value : '');
      }
      const value = row[col.accessorKey as keyof T];
      return escapeCsvCell(value !== null && value !== undefined ? value : '');
    }).join(','));

    csvRows.push(headers);
    csvRows.push(...dataRows);

    const csvString = csvRows.join('\n');
    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${getFormattedFileName()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">
          <Download className="mr-2 h-4 w-4" /> 
          Export Data
          {dateRange?.from && dateRange?.to && (
            <span className="ml-2 text-xs text-muted-foreground">
              ({format(dateRange.from, 'MMM dd')} - {format(dateRange.to, 'MMM dd')})
            </span>
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={generatePdf}>
          <FileText className="mr-2 h-4 w-4" />Export as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={generateCsv}>
          <FileSpreadsheet className="mr-2 h-4 w-4" />Export as CSV
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};